import os
import time

hostnames = [
    'Github.com',
    #Du Kan bare Add Din Egen Webside/Ip Den Skal Pinge
]
for hostname in hostnames:
    response = os.system('ping  ' + hostname)

    if response == 0:
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
	print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
        print (hostname, 'Pinger')
    else:
        print (hostname, 'Invalid IP')  
        print (hostname, 'Invalid IP')  
        print (hostname, 'Invalid IP')  
        print (hostname, 'Invalid IP')  
        print (hostname, 'Invalid IP')  
        print (hostname, 'Invalid IP')  
        print (hostname, 'Invalid IP')  
        print (hostname, 'Invalid IP')     
    #Venter På Response
        print ('')
        print ('')
        print ('')
        print ('')
        print ('')
        print ('')
        print("Alle Angivet Websider har fåedt Tjeket Status")